import { parseAbi } from "viem";

// ERC-3643 IERC3643 — own members only (IERC20 excluded), transcribed from specs/erc-3643.md.
// Interface return types IIdentityRegistry / ICompliance are addresses in the ABI.

export const erc3643Abi = parseAbi([
  "event UpdatedTokenInformation(string _newName, string _newSymbol, uint8 _newDecimals, string _newVersion, address _newOnchainID)",
  "event IdentityRegistryAdded(address indexed _identityRegistry)",
  "event ComplianceAdded(address indexed _compliance)",
  "event RecoverySuccess(address _lostWallet, address _newWallet, address _investorOnchainID)",
  "event AddressFrozen(address indexed _userAddress, bool indexed _isFrozen, address indexed _owner)",
  "event TokensFrozen(address indexed _userAddress, uint256 _amount)",
  "event TokensUnfrozen(address indexed _userAddress, uint256 _amount)",
  "event Paused(address _userAddress)",
  "event Unpaused(address _userAddress)",
  "function onchainID() view returns (address)",
  "function version() view returns (string)",
  "function identityRegistry() view returns (address)",
  "function compliance() view returns (address)",
  "function paused() view returns (bool)",
  "function isFrozen(address _userAddress) view returns (bool)",
  "function getFrozenTokens(address _userAddress) view returns (uint256)",
  "function setName(string _name)",
  "function setSymbol(string _symbol)",
  "function setOnchainID(address _onchainID)",
  "function pause()",
  "function unpause()",
  "function setAddressFrozen(address _userAddress, bool _freeze)",
  "function freezePartialTokens(address _userAddress, uint256 _amount)",
  "function unfreezePartialTokens(address _userAddress, uint256 _amount)",
  "function setIdentityRegistry(address _identityRegistry)",
  "function setCompliance(address _compliance)",
  "function forcedTransfer(address _from, address _to, uint256 _amount) returns (bool)",
  "function mint(address _to, uint256 _amount)",
  "function burn(address _userAddress, uint256 _amount)",
  "function recoveryAddress(address _lostWallet, address _newWallet, address _investorOnchainID) returns (bool)",
  "function batchTransfer(address[] _toList, uint256[] _amounts)",
  "function batchForcedTransfer(address[] _fromList, address[] _toList, uint256[] _amounts)",
  "function batchMint(address[] _toList, uint256[] _amounts)",
  "function batchBurn(address[] _userAddresses, uint256[] _amounts)",
  "function batchSetAddressFrozen(address[] _userAddresses, bool[] _freeze)",
  "function batchFreezePartialTokens(address[] _userAddresses, uint256[] _amounts)",
  "function batchUnfreezePartialTokens(address[] _userAddresses, uint256[] _amounts)",
]);
